

source 'http://ruby.sankuai.com/' do
  gem 'linkmap_ios', :path => '/Users/chengguozhi/Desktop/Gitlinkmap/linkmap_ios'
end

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
